---
title: "Untitled"
output: html_document
---
```{r}
library(tidyverse)
library(lubridate)
library(gganimate)
library(grid)
library(png)
library(extrafont)
```


```{r}
open_table_full <- read_csv("state_of_industry_data.csv") %>%
  janitor::clean_names()
```

```{r}
open_table_canadian <- open_table_full %>%
  filter(name %in% c("Canada", "Ontario", "Quebec", "Toronto", "Alberta", "Calgary", "Edmonton", "Montréal", "Vancouver")) %>%
  gather(date, percent_change_yoy, -type, -name) %>%
  mutate(date = paste0("2020-0", str_extract(date, "[0-9]"), "-", str_extract(date, "[0-9]{2}")),
         date = ymd(date),
         date_labels = paste(month(date, label = TRUE), day(date))) %>%
  arrange(date)
```

```{r}
open_table_canadian %>%
  ggplot(aes(x = date, y = percent_change_yoy, colour = name)) +
  geom_line() +
  scale_colour_manual(values = rep("grey", times = n_distinct(open_table_canadian$name))) +
  geom_line(data = open_table_canadian %>%
              filter(name == "Toronto"), colour = "blue") +
  scale_y_continuous(breaks = seq(50, -100, by = -25),
                     labels = c("50%", "25%", "0%", "-25%", 
                                "-50%", "-75%", "-100%")) +
  expand_limits(y = 50) 
```

```{r}
ford_12 <- rasterGrob(
  readPNG("ford_mar_12.PNG"), 
  interpolate=TRUE)

ford_17 <- rasterGrob(
  readPNG("state_of_emerg.PNG"), 
  interpolate=TRUE)

```

```{r, fig.height = 9, fig.width = 16, units = "in"}
p <- open_table_canadian %>%
  filter(name == "Toronto" & date >= as.Date("2020-03-01")) %>%
  ggplot(aes(x = date, y = percent_change_yoy, fill = percent_change_yoy)) +
  geom_col(aes(group = date), width = 1) +
   annotation_custom(ford_12, 
                     ymin = 20, ymax= 80,
                     xmin = as.Date("2020-03-01"), 
                     xmax =  as.Date("2020-03-14")) +
  geom_curve(data = open_table_canadian %>% filter(date == as.Date("2020-03-12")), 
             aes(x = as.Date("2020-03-12"), 
                 y = 20, 
                 xend = as.Date("2020-03-12"), 
                 yend = 1), 
             colour = 'white', 
             size = 1, 
             curvature = 0,
             arrow = arrow(length = unit(0.3, "cm"))) +
  
  annotation_custom(ford_17, 
                     ymin = 20, ymax= 80,
                     xmin = as.Date("2020-03-16"), 
                     xmax =  as.Date("2020-03-29")) +
  geom_curve(data = open_table_canadian %>% filter(date == as.Date("2020-03-17")), 
             aes(x = as.Date("2020-03-17"), 
                 y = 20, 
                 xend = as.Date("2020-03-17"), 
                 yend = 1), 
             colour = 'white', 
             size = 1, 
             curvature = 0,
             arrow = arrow(length = unit(0.3, "cm"))) +
  
  labs(title = "March Toronto Restuarant Shutdown Timeline\nCOVID-19 scare causes Mayor Doug Ford to enact state of emergency in Ontario.",
       subtitle = "\nShown below is year-over-year seated customers at restaurants on OpenTable network \nacross all channels: online reservations, phone reservations, and walk-ins.",
       caption = "Viz by @datajake; SOURCE: https://www.opentable.com/state-of-industry") +
  scale_fill_gradient2(low = "red", high = "white", midpoint = 25) +
  scale_y_continuous(name = "Year-over-Year Change",
                     breaks = seq(100, -100, by = -50),
                     labels = c("100%", "50%", "0%", 
                                "-50%", "-100%")) +
  scale_x_date(name = "Month of March 2020 —>",
               breaks = c(as.Date("2020-03-01"), as.Date("2020-03-31")),
               labels = c( "Mar 01", "Mar 31")) +
  expand_limits(y = 100, x = as.Date("2020-03-31")) +
  theme(text = element_text(colour = "white", family = "Montserrat ExtraBold"),
        plot.title = element_text(size = 20),
        plot.subtitle = element_text(size = 16, family = "Merriweather Black"),
        plot.caption = element_text(face = "italic", colour = "grey 50"),
        legend.position = "none",
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_line(colour = "grey20"),
        panel.grid.major.x = element_blank(),
        axis.text.x = element_text(face = "bold"),
        axis.text.y = element_text(face = "bold"),
        axis.ticks = element_blank(),
        axis.text.x.bottom = element_text(colour = "white"),
        axis.text.y.left = element_text(colour = "white"),
        panel.background = element_rect(fill = "black", colour = "white"),
        plot.background = element_rect(fill = "black"),
        plot.margin = margin(1, 1, 1, 1, "cm"))

p
```

```{r}
animated_plot <- p +
  transition_reveal(date) +
  shadow_trail()
```

```{r}
options(gganimate.dev_args = list(height = 9, width = 16, units = 'in', type = "cairo", res = 144))

animate(plot = animated_plot,
        fps = 10,
        duration = 12,
        renderer = gifski_renderer("animations/toronto_restaurant_shutdown.gif"))
```

